#!/bin/bash

DIR=/usr/src/app

get_config_url() {
    if [[ ${CONFIG_FILE_URL} ]]; then
        curl -s $CONFIG_FILE_URL -o config.env
    fi
}

get_repo_link() {
    if [[ -f config.env ]]; then
        export $(echo "from os import environ
from dotenv import load_dotenv

load_dotenv('config.env', override=True)

UPSTREAM_REPO = environ.get('UPSTREAM_REPO')
UPSTREAM_BRANCH = environ.get('UPSTREAM_BRANCH')

print(f'UPSTREAM_REPO={UPSTREAM_REPO}')
print(f'UPSTREAM_BRANCH={UPSTREAM_BRANCH}')" | python3)
    fi

    if [[ ${UPSTREAM_REPO} && ${UPSTREAM_BRANCH} ]]; then
        echo "Detected UPSTREAM REPO and UPSTREAM BRANCH"
    else
        UPSTREAM_REPO=https://github.com/ahadz-git/mirror-leech-telegram-bot
        UPSTREAM_BRANCH=h-code
    fi
}

git_pack() {
    [ -d .git ] &&
    rm -rf .git
    git init -q
    git clone $UPSTREAM_REPO $UPSTREAM_BRANCH $DIR
    cd $DIR
}

keep_alive() {
    while true
    do
        curl -s https://$HEROKU_APP_NAME.herokuapp.com -o /dev/null
        sleep 15m
    done
}

start_bot() {
    get_config_url
    get_repo_link
    git_pack &&
    keep_alive &
    python3 -m bot
}

start_bot
